import { Home } from "./Pages/Home";
import { Navbar } from "./Components/Navbar";
import { Jumbotron } from "./Components/Jumbotron";
import { AbsImg } from "./Components/AbsImg";
import { AboutUs } from "./Components/AboutUs";
import { Restaurants } from "./Components/Restaurants";
import { Hotels } from "./Components/Hotels";
import { ContactUs } from "./Components/ContactUs";
import { Footer } from "./Components/Footer";
export  {Home,Navbar,Jumbotron,AbsImg,AboutUs,Restaurants,Hotels,ContactUs,Footer};